spring:
  application:
    name: beershop
  datasource:
    url: jdbc:h2:mem:beershopdb
    driver-class-name: org.h2.Driver
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
